name: finance_wallet
description: "A modern finance wallet application with beautiful UI/UX"
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/mixin27/finance-wallet
issue_tracker: https://github.com/mixin27/finance-wallet/issues

workspace:
  - packages/finance_auth

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # internal
  finance_auth:
    path: packages/finance_auth

  # State Management & Architecture
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Routing
  go_router: ^17.0.1

  # HTTP & API
  dio: ^5.9.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0

  # Local Storage
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  path: ^1.9.1
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5

  # UI & Animations
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^2.0.1
  fl_chart: ^1.1.1
  intl: ^0.20.2

  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0

  # Icons & Images
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

  # Utils
  freezed_annotation: ^3.1.0
  logger: ^2.6.2
  uuid: ^4.5.2
  dartz: ^0.10.1
  envied: ^1.3.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  retrofit_generator: ^10.2.0
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  envied_generator: ^1.3.2
  drift_dev: ^2.30.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
